[package]
name = "rusty_nanograd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

rand = "0.8.5"

[dependencies]
rand = "0.8.5"
